src/styles/Colors.tsx, src/styles/Fonts.tsx, src/styles/GlobalStyles.tsx
globalStyle 설정
Fonts, Colors 파일 생성
=> setting: globalStyle 설정

src/components/layouts/navigations/TheNavigation.tsx
TheNavigation 파일 수정
오류해결
마이플리와 에드플리 페이지가 404 오류로 켜지지 않는 문제를 해결했습니다
제가 올린 사진대로 수정하시면 페이지가 보입니다
components - layouts - navigations - TheNavigation.tsx 파일 수정
my-playlist / add-playlist 로 수정해주시면 됩니다.
components - layouts - navigations - TheNavigation.tsx 파일 수정
my-playlist / add-playlist 로 수정해주시면 됩니다.
-
=> [BugFix] TheNavigation 파일 수정

src/components/layouts/headers/TheHeader.tsx, src/routes/pages/AddPlaylist.tsx, src/stores/addPlaylist.ts
완료버튼 기능 및 글자수 제한 기능 추가
- 완료버튼 기능 구현
+ 기존 AddPlaylist 컴포넌트에 있던 완료버튼을 헤더 위에 있도록 구현하였습니다.
+ AddPlaylist 와 TheHeader 을 연결시켜주었고, 상태관리를 위한 addPlaylist (store) 를 추가하였습니다.
+ 데이터베이스 및 useAddPlaylistStore 를 addPlaylist (store) 에 옮겨줬습니다. 
+ TheHeader 에 필수요소를 입력하면 완료버튼 표시가 뜨도록 해줬습니다.
- 스타일 추가
+ 스크롤 스타일 변경되었습니다.
+ 완료버튼 스타일 추가되었습니다.
- 글자수 제한 기능을 추가하였습니다.
+ 기존 제목에만 글자제한이 있었는데 내용에도 글자제한을 추가하였습니다.
완료버튼 기능 및 글자수 제한 기능 추가
스타일 추가
z-index 를 1로 낮춰줬습니다.
뒤에 세미클론 css 빼고 빼줬습니다.
링크 2개 올렸을때부터 완료버튼 활성화되도록 바꿨습니다. (videoUrls.length > 1 && videoTitle)
새로 클론 받은 후 변경 된 코드를 입혀줘서 충돌 없을 것 같습니다!
머지 후 브랜치 삭제 부탁드려요~!
=> [feature] 완료버튼 기능 및 글자수 제한 기능 추가 #41

src/components/layouts/navigations/NavigationItem.tsx, src/components/layouts/navigations/TheNavigation.tsx
navigation 경로를 url과 맞춰 찾도록 수정 (isActive 수정), + 버튼 눌렀을 때는 색상 변경되지 않도록 설정
navigation 경로를 location을 이용해 찾도록 수정 (isActive를 수동으로 설정하지 않아도 됨)
+ 버튼 눌렀을 때 다른 버튼과 같이 색상이 바뀌는 버그가 있어서 바뀌지 않도록 수정
navigation 경로를 location을 이용해 찾도록 수정 (isActive를 수동으로 설정하지 않아도 됨)
+ 버튼 눌렀을 때 다른 버튼과 같이 색상이 바뀌는 버그가 있어서 바뀌지 않도록 수정
=> [bug] navigation 경로 수정, + 버튼 색상 바뀌지 않도록 수정

src/components/playlist/Playlist.tsx, src/routes/index.tsx
홈에서 보이는 플레이리스트 컴포넌트를 수정하였습니다.
컴포넌트 폴더안 플레이리스트 컴포넌트에 있는 하트 아이콘 클릭시 채워진 색상 하트아이콘으로 변경되고,
홈에서 보이던 수정, 삭제 버튼과 기능을 삭제했습니다.
day.js에서 불러온 시간이 0000년 00월 00일에서 업로드 시간 기준 몇 분, 몇 시간 전 으로 변경되었고,
프로필 아이콘을 삭제하고 유저의 사진 불러오기로 대체하였습니다.
- components안에 있는 playlist.tsx 빈 하트 아이콘 클릭시 채워진 하트 아이콘으로 변경
- 하트, 코멘트, 북마크 아이콘 색상 변경
- 홈에서 보이던 수정, 삭제 버튼과 기능을 삭제
- day.js 시간 불러오기 변경
- 프로필 아이콘 삭제
- 유저 사진 데이터 불러오기
=> [Feature] 플레이리스트 컴포넌트 수정 #46

src/components/common/LongButton.tsx, src/components/layouts/headers/TheHeader.tsx, src/routes/pages/Profile2.tsx
프로필페이지 UI 구현
프로필페이지 UI 구현
- 프로필페이지 스타일 추가
- TheHeader 수정 버튼 추가 (기능x)
- LongButton 에 cursor: pointer 추가
- 프로필페이지에 로그아웃 누르면 로그인 페이지로 돌아가는 부분, 로그인 파일이 사인인으로 바껴서 navigate(/SignIn) 으로 변경
=> Feature/ 프로필페이지 UI 구현 #60

src/components/playlist/Playlist.tsx, src/hooks/useToggleBookmark.ts, src/routes/pages/Bookmark.tsx
북마크페이지 UI 구현 했습니다. 
- 플레이리스트와 북마크 페이지의 UI구현
- 북마크아이콘은 fa6으로 아이콘변경 
- 북마크페이지에서 북마크 아이콘 누르면 모달로 선택할 수 있게끔 모달 컴포넌트 연결했습니다.
- 삭제누르면 북마크 해제됩니다.
북마크 아이콘이 서로 달라 크기와 모양이 달라져
비어있는 북마크,채워져있는 북마크 다 fa6 리액트 아이콘으로 변경하였습니다.
=> [feature] 북마크 UI 구현

src/api/VideoData.ts, src/components/common/PlaylistDetail.tsx, src/components/playlist/Playlist.tsx, src/hooks/useCreateComment.ts, src/hooks/useUpdatePlaylist.ts, src/routes/pages/Bookmark.tsx, src/routes/pages/Home.tsx, src/routes/pages/PlaylistDetail.tsx, src/stores/addPlaylist.ts, src/stores/useBookmark.ts
플레이리스트 상세보기 페이지에 유저가 업로드한 동영상을 불러오고,
styles에 버그가 생겨 해결했습니다. 
상세보기 페이지에 있는 내용을 공통 컴포넌트로 작업할 예정입니다.
상세보기 페이지 생성 퍼블리싱과 데이터 불러오기
- 상세보기 페이지 동영상 데이터 불러오기
- theme 오류 코드 해결
=> [Style] 플레이리스트 상세보기 페이지 퍼블리싱 및 버그 수정

src/components/bookmarks/BookmarkList.tsx, src/components/bookmarks/BookmarkModal.tsx, src/hooks/useFetchUserBookmark.ts, src/hooks/useToggleBookmark.ts, src/routes/pages/Bookmark.tsx
북마크 컴포넌화하기
북마크 컴포넌화하기
모달추가
토스트추가 -> 화면에 안뜨는 오류 발생 ( 고쳐야함 )
=> [feature]북마크 컴포넌트화

src/components/common/PlaylistDetail.tsx, src/components/layouts/headers/TheHeader.tsx, src/components/layouts/navigations/NavigationItem.tsx, src/components/layouts/navigations/TheNavigation.tsx
savedMyPlaylist 페이지 UI 수정 및 헤더, 네브바 수정
- savedMyPlaylist 페이지 UI 수정
- 헤더 수정: backbutton cursor 효과, 디테일 페이지와 연결
- 네브바 수정: hover 효과
- savedMyPlaylist 페이지 UI 수정
- 헤더 수정: backbutton cursor 효과, 디테일 페이지와 연결
- 네브바 수정: hover 효과
=> [Feature] savedMyPlaylist 페이지 UI 수정 및 헤더, 네브바 수정

src/components/common/Category.tsx, src/components/playlist/Playlist.tsx, src/hooks/useFetchPlaylist.ts, src/hooks/useFetchPlaylists.ts, src/routes/pages/AddPlaylist.tsx, src/routes/pages/Home.tsx, src/stores/addPlaylist.ts
카테고리 공통컴포넌트에 기능 추가
카테고리 공통컴포넌트에 기능 추가
- AddPlaylist.tsx
+ 카테고리를 불러오기 위한 코드들 추가
+ 카테고리 선택 아무것도 안할시 완료버튼 비활성화
+ 링크 추가 시 링크제목(?) 제한 걸었음
- Category.tsx
+ 기본값 '전체' 로 지정
+ 타입 지정
+ 카테고리 다중 선택 가능
+ 선택한 카테고리 다시 클릭 시 선택 해제됨
- addPlaylist.ts
categories 와 selectedCategories 추가
- Home.tsx
카테고리가 실행되도록 (?) 카테고리 코드만 추가하고 다른건 변경 X
+ import { Category } from '@/components/common/Category'
+ const [selectedCategory, setSelectedCategory] = useState<string>('전체')
+ const filteredData = selectedCategory
? data?.filter(pl => Array.isArray(pl.categories) && pl.categories.includes(selectedCategory))
: data;
+ <Category
selectedCategories={selectedCategory ? [selectedCategory] : []} 
onSelectCategory={categories => setSelectedCategory(categories[0])} 
/>
- Playlist.tsx
카테고리 타입 지정 `categories: string[ ]`
- …
=> [Feature] 카테고리 공통컴포넌트에 기능 추가

src/components/common/Category.tsx, src/components/layouts/headers/TheHeader.tsx, src/routes/pages/AddPlaylist.tsx, src/routes/pages/Profile.tsx
카테고리 호버 삭제 및 추가페이지 스타일 변경 및 프로필페이지 스타일 변경
카테고리 호버 삭제 및 추가페이지 스타일 변경 및 프로필페이지 스타일 변경
- 카테고리 호버 삭제
- 추가페이지 스타일 변경
+ 사이드 간격 추가 (margin-left 18px)
+ 동영상 링크 추가되는 부분 텍스트 12px -> 14px 로 변경 및 컨테이너 크기 키워줌
- 프로필 페이지도 추가페이지에 맞춰 사이드 간격 추가 및 gap 을 10px 로 줄임
비공개로 게시글 업로드시 토스트는 뜨지 않고 홈으로 이동만 하도록 변경하였습니다. (TheHeader 컴포넌트)
=> [Style] 카테고리 호버 삭제 및 추가페이지 스타일 변경 및 프로필페이지 스타일 변경 #92

src/api/firebaseAuth.ts, src/components/bookmarks/BookmarkItem.tsx, src/components/bookmarks/BookmarkModal.tsx, src/components/common/Toast.tsx, src/components/playlist/Playlist.tsx, src/hooks/useFetchComments.ts, src/hooks/useFetchUser.ts, src/routes/pages/Home.tsx, src/routes/pages/SignIn.tsx
파이어베이스 Users 컬렉션 생성
- firebaseAuth.ts 생성
- SignIn 수정
- 북마크아이템, 북마크모달, 토스트 CSS 변경
- 파이어베이스 Users 컬렉션 생성
파이어베이스에 Users 컬렉션을 생성해서 userId가 연결됩니다.
=> [Feature] 파이어베이스 Users 컬렉션 생성 #101

src/components/EditPlaylistModal.tsx, src/components/layouts/headers/TheHeader.tsx, src/components/layouts/navigations/TheNavigation.tsx, src/components/playlist/PlaylistDetail.tsx, src/routes/pages/AddPlaylist.tsx, src/routes/pages/Bookmark.tsx, src/routes/pages/DeleteVideos.tsx, src/routes/pages/EditPlaylistInfo.tsx, src/routes/pages/MyPlaylist.tsx, src/routes/pages/Profile.tsx, src/styles/Theme.tsx
헤더 이름 및 버튼 수정, 편집 모달 위치 수정
헤더 이름 및 버튼 수정, 편집 모달 위치 수정
편집 모달 네비게이션 가리도록 위치 수정 및 전체 세로 길이 조정
헤더 한글로 변경 및 버튼 생성과 이름 수정
- 편집 모달 네비게이션 가리도록 위치 수정 및 전체 세로 길이 조정
- 헤더 한글로 변경
=> [Style] 헤더 이름 및 버튼 수정, 편집 모달 위치 수정

src/routes/pages/AddPlaylist.tsx
AddPlaylist 파일 코드 새로 수정
수정한 내용이나 추가한 기능에 대해 자세히 설명해 주세요.
=> hotfix: addPlaylist 코드 수정

src/api/VideoData.ts, src/components/playlist/Playlist.tsx, src/components/playlist/PlaylistDetail.tsx, src/hooks/useExtractVideoId.ts, src/hooks/useFetchPlaylistData.ts, src/hooks/useHeartData.ts, src/routes/pages/AddPlaylist.tsx
videoId 를 통해 안 불러와졌던 썸네일을 불러오는데 성공했지만 아직 동영상 재생은 되지 않습니다.
컴포넌트 폴더안에 플레이리스트 폴더 안에 있던 공통컴포넌트인 Playlist.tsx 코드를 리팩토링 했습니다.
공통 컴포넌트 정리
- hooks ⇒ useExtractVideoId.ts 생성
- hooks ⇒ useHeartData.ts 생성
- hooks ⇒ usePlaylistData.ts 생성
공통컴포넌트 하나에 담겨져있던 코드가 hooks를 생성해 정리했습니다.
정리된 코드
=> [Bug] videoId 불러오기 버그 수정 및 playlist.tsx 코드 리팩토링

src/components/playlist/PlaylistDetail.tsx, src/hooks/useFetchPlaylists.ts, src/routes/pages/AddPlaylist.tsx, src/routes/pages/Home.tsx, src/stores/addPlaylist.ts
비공개 설정시 삭제안되는 문제 해결 및 DB 통합
비공개 설정시 삭제안되는 문제 해결 및 DB 통합
- PlaylistDetail
+ PublicPlaylists 부분 삭제
- useFetchPlaylists.ts
+ PublicPlaylists 부분 삭제
- AddPlaylist.tsx
+ `e` 에서 타입에러 나는 것 로직 수정
+ 로직 추가
- addPlaylsits.ts
+ PublicPlaylists 삭제
- PublicPlaylists 에 데이터 안들어가고 Playlists 에만 데이터 들어가는 것 확인
- 비공개 선택 후 게시글 올라가면 마이플레이리스트에서만 보이는지 확인
- 비공개 게시글의 디테일 페이지가 잘 작동되는지 확인
- 비공개 게시글이 삭제되는지 확인
=> [Bug] 비공개 설정시 삭제안되는 문제 해결 및 DB 통합 #125

src/components/Comments/Comments.tsx, src/components/Comments/CommentsModal.tsx, src/components/playlist/PlaylistDetail.tsx, src/hooks/usePlaylistData.ts, src/hooks/useSortablePlaylist.ts, src/hooks/useToggleDescription.ts, src/hooks/useVideoTitles.ts
공통 컴포넌트 comments modal의 UI를 수정하였습니다.
아까 만졌던 hooks도 같이 추가되었는데 일단 무시해주시면 됩니다.
- 아이콘 추가
- 유저 사진 삭제
- 댓글 배치 변경
- css 변경
- comments.tsx 수정
- commentsModa.tsx 수정
- comments.tsx 수정
- commentsModa.tsx 수정
- PlaylistDetail.tsx 수정
=> [Feature] comments modal UI 수정 #102

src/api/likes.ts, src/hooks/useLikeData.ts, src/routes/index.tsx
좋아요 숫자 데이터는 공용으로 보이게하고 하트 아이콘은 개인이 하게 설정했는데 되는지 한번만 확인좀
=> [Feature] 파이어베이스 좋아요 테스트

src/components/bookmarks/BookmarkItem.tsx, src/components/playlist/Playlist.tsx, src/hooks/useFetchPlaylistData.ts
[bug]내플리 북마크설정  재발 개선 완
내 플리 북마크 아이콘 및 기능 안되게 수정
- Playlist
- useFetchPlaylistData ( 유저정보 import 추가, isOwner구분 추가)
- 북마크 부수적인 주석들 ,,, 삭제
=> [bug]내플리 북마크설정  재발 개선 완

src/components/playlist/Playlist.tsx, src/hooks/useLikeData.ts
파이어베이스 데이터베이스에 좋아요를 연결하고 하트는 유저 개인만 설정하고
숫자데이터는 공통으로 볼수있도록 설정했습니다. 이제까지 안됐던 이유는 userId를 설정 안해서
사용자가 누구인지 인식하지 못해서 그랬습니다.
- Playlist.tsx 수정
- likes.ts 수정
- useLikeData.ts 수정
코드만 수정되고 다른부분은 수정된거 없습니다.
=> [Feature] 파이어베이스 DB 좋아요 연결 #118

src/components/playlist/EditPlaylistModal.tsx, src/components/playlist/PlaylistDetail.tsx
케밥케이스 추가, 모달 수정, 편집페이지 경로 수정, 기타 스타일 수정
케밥케이스 추가, 모달 수정, 편집페이지 경로 수정, 기타 스타일 수정
드래그 앤 드롭 시 grab으로 바뀌도록 수정
=> [Style] 케밥케이스 추가, 모달 수정, 편집페이지 경로 수정, 기타 스타일 수정

src/hooks/usePlaylistData.ts, src/routes/pages/EditProfile.tsx, src/routes/pages/Home.tsx, src/stores/editProfile.ts
프로필 편집페이지 사진 변경 추가
프로필 편집페이지 사진 변경 추가
- EditProfile, editProfile 에 사진 추가할 수 있도록 로직 추가
- Home 에 불필요한 로직 삭제 (프로필변경 관련)
- usePlaylistData 에 프로필 업데이트 되면 패치하도록 로직 추가 (진행중)
- 프로필 변경했을때 프로필 페이지에서만 바뀜 (데이터는 잘 바뀐걸로 확인됨)
- 홈이나 다른곳에서도 바뀌게 하려고 방법 고안중
=> [ Feature] 프로필 편집페이지 사진 변경 추가 (진행중) #89

src/components/Comments/Comments.tsx, src/components/Comments/CommentsModal.tsx, src/components/playlist/EditPlaylistModal.tsx, src/components/playlist/PlaylistDetail.tsx
코멘트 UI를 변경하였으니 PR을 받아주세요.
코멘트에 들어가는 UI를 변경하였습니다.
기존에 있던 EditPlaylistModal과 통일감있도록 변경하였습니다.
작업하면서 playlistDetail에 주석이 추가되었습니다.
=> [Style] comments modal UI 변경 #145

src/components/bookmarks/BookmarkItem.tsx, src/hooks/useFetchBookmark.ts
[bug]북마크썸네일 버그 및 북마크,드래그 위치 수정
북마크 썸네일 안나오는 곳 개선하기
디테일페이지와 맞춰서 북마크아이콘 왼쪽
드래그앤드롭 아이콘 오른쪽으로 변경
=> [bug]북마크썸네일 버그 및 북마크,드래그 위치 수정

src/components/playlist/EditPlaylistModal.tsx, src/components/playlist/PlaylistDetail.tsx, src/hooks/useDeleteVideo.ts, src/routes/pages/SavedPlaylists.tsx
비디오 삭제 기능 구현 및 디테일 페이지 스타일 수정
공개/비공개 설정에 따라 아이콘 다르게 렌더링해주는 기능 추가
디테일 페이지 재생목록 부분 UI 수정
useDeleteVideo 훅 생성 후 비디오 삭제하는 기능 구현 (렌더링 기능 수정 필요)
각 아이콘에 조건 설정하여 그에 따라 렌더링되도록 수정
디테일 페이지 재생목록 부분 UI 수정
- 공개된 플레이리스트는 자물쇠 열림, 비공개는 자물쇠 닫힘
- 다른 유저의 플레이리스트 상세페이지
- 내 플레이리스트 상세 페이지
=> [Feature] 비디오 삭제 기능 구현 및 디테일 페이지 스타일 수정

src/components/bookmarks/BookmarkItem.tsx, src/routes/pages/Bookmark.tsx, src/routes/pages/MyPlaylist.tsx, src/routes/pages/SavedPlaylists.tsx
마이플리 토스트 개선
마이플리 삭제 시 토스트 짧게 나오는 현상 개선
토스트 컴포넌트를 SavedPlaylists파일에서 MyPlaylist로 이동
토스트랑 상관없지만 북마크 드래그 아이콘 명칭 디테일페이지랑 똑같이 함
( drag-handle -> handle )
=> [bug]마이플리 토스트 개선

src/components/common/TheModal.tsx, src/components/layouts/headers/TheHeader.tsx, src/routes/pages/EditProfile.tsx, src/stores/editProfile.ts
프로필 수정페이지에서 변경시 파이어베이스 데이터와 연동되면서 자동으로 변경되도록 구현
프로필 수정페이지에서 변경시 파이어베이스 데이터와 연동되면서 자동으로 변경되도록 구현
- 개발서버에서만 프로필 변경이 이루어지고 파이어베이스 데이터는 변경이 안되는 문제 해결 (컬렉션 이름 잘못적음)
- 프로필 사진 변경 가능
- 프로필 닉네임 변경 가능
- 수정페이지에서 수정 후 뒤로가기 버튼을 누르면 모달창이 뜸 (이 과정에서 TheModal.tsx 로직 수정)
- 수정페이지 input 창 디자인 약간 수정
정말 어렵다 오타 안나는거
=> [Feature] 프로필 수정페이지 기능 개발 #89

src/api/playlistApi.tsx, src/components/infiniteScroll/InfiniteScroll.tsx, src/hooks/useInfiniteScroll.ts, src/routes/pages/Home.tsx
무한스크롤을 불러왔으니 PR요청을 받아주세요.
- useInfiniteScroll.ts 생성
- playlistApi.tsx 생성
- InfiniteScroll.tsx 생성
- Home.tsx 에 InfiniteScroll 불러오기
페이지 마지막으로 갈시 위에 올라갔던 데이터들을 다시 보여주는 무한스크롤을 구현했습니다.
Uploading 화면 기록 2024-09-25 오후 8.50.19.mov…
=> [Feature] 무한스크롤 구현 #148

src/hooks/useInfiniteScroll.ts
무한스크롤 데이터 최대 100개 제한 걸어서 다시 올립니다.
=> [Bug] infinite scroll 긴급 수정 #163

package-lock.json, package.json, src/routes/pages/AddPlaylist.tsx
추가페이지 툴팁 추가 및 글자간격 늘림
- 추가페이지 툴팁 추가
- 글자간격 늘렸습니다
- `*` 을 왼쪽으로 옮겼습니다
tooltip 라이브러리 깔았습니다
말풍선 위쪽에 하면 헤더에 가려지고, 아래에 하면 왼쪽에 너무 붙어서 오른쪽으로 했습니다..
=> [Feature] 추가페이지 툴팁 추가 및 글자간격 늘림 #161

package-lock.json, package.json, src/components/Comments/CommentsModal.tsx, src/hooks/useCreateComment.ts
댓글모달에 들어가면 남의 댓글까지 삭제할수있는 버그를 발견해서 수정했습니다.
댓글삭제 아이콘을 안보이도록 작업했습니다.
플레이리스트의 uid가 동일할시 삭제 아이콘이 나타나게 하도록 변경했습니다.
=> [Bug] 댓글 삭제 버그 수정 #152

src/components/playlist/EditPlaylistModal.tsx, src/components/playlist/PlaylistDetail.tsx, src/hooks/useDeleteVideo.ts, src/hooks/useFetchPlaylistById.ts, src/routes/pages/BookmarkedPlaylist.tsx
비디오 삭제 기능 수정 및 렌더링 로직 구현
비디오 삭제 기능 수정 및 렌더링 로직 구현
디테일 페이지 스타일 수정
- 비디오 삭제 기능 수정: 삭제기능을 구현하였는데 선택한 비디오말고 다른 비디오가 삭제되는 버그가 발견되어 코드 수정
- 비디오 삭제 후 화면에 렌더링하는 기능 구현: 플레이리스트 불러오는 api와 useDeleteVideo 훅 사용
- 디테일 페이지 스타일 수정: 모달 배경 투명도 조절, 아이콘 색상 변경, 재생목록에 overflow: scroll
=> [Feature] 비디오 삭제 기능 수정 및 렌더링 로직 구현

package-lock.json, src/components/playlist/PlaylistDetail.tsx
[feature]북마크디테일페이지 케밥,햄버거아이콘 안보이게 하기
수정한 내용이나 추가한 기능에 대해 자세히 설명해 주세요.
=> [feature]북마크디테일페이지 케밥,햄버거아이콘 안보이게 하기

src/routes/pages/AddPlaylist.tsx
추가페이지 헤더 한글명으로 변경
수정한 내용이나 추가한 기능에 대해 자세히 설명해 주세요.
=> [Style] 추가페이지 헤더 한글명으로 변경 #174

src/hooks/useFetchBookmark.ts, src/hooks/useFetchUserBookmark.ts, src/hooks/useToggleBookmark.ts, src/routes/pages/Bookmark.tsx
[feature]북마크 드래그 미완성,ORDER필드추가
마크 드래그 미완성,
북마크 훅에 ORDER 필드 추가 ( 나중에 DnD 구현을 위한 필드 )
=> [feature]북마크 드래그 미완성,ORDER필드추가

.github/workflows/playwright.yml, .gitignore, package-lock.json, package.json, playwright.config.ts, src/components/Comments/CommentsModal.tsx, src/components/layouts/Container.tsx, src/components/layouts/headers/TheHeader.tsx, src/components/playlist/EditPlaylistModal.tsx, src/components/playlist/Playlist.tsx, src/components/playlist/PlaylistDetail.tsx, src/routes/pages/AddPlaylist.tsx, src/routes/pages/EditPlaylistInfo.tsx, src/routes/pages/NotFound.tsx, src/routes/pages/SignIn.tsx, tests-examples/demo-todo-app.spec.ts, tests/example.spec.ts, tests/tests/signIn.spec.ts
test 코드 생성 및 페이지 스타일링 수정
테스트 코드 작성 (로그인 페이지)
플레이리스트 추가 페이지와 플레이리스트 정보 수정 페이지 letter-spacing 수정
플레이리스트 편집 페이지에서 데이터 가져올 때 글자수는 반영 안되는 버그 (글자수 부분만 수정, 데이터 연동은 안됨)
플레이리스트 편집 페이지 레이아웃 조정 (제목/설명/카테고리/공개 설정 사이 여백 더 주기)
플레이리스트 상세페이지 재생목록 스크롤과 케밥 아이콘 겹치지 않게 padding 추가
명확한 UI를 보여주기 위해서 구현 화면에 테두리 설정
비디오 삭제 바텀시트 위치 수정
playwright 설치가 필요합니다
=> [Feature] test 코드 생성 및 페이지 스타일링 수정

README.md
=> [Style] readme작성 #169
